# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver_profile',
            old_name='location',
            new_name='city',
        ),
    ]
