# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20171210_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_profile',
            name='Free_space',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
