# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider_profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
